export const passwordResetConfirmTypes = {
    PASSWORD_RESET_CONFIRM_REQUEST: 'PASSWORD_RESET_CONFIRM_REQUEST',
    PASSWORD_RESET_CONFIRM_SUCCESS: 'PASSWORD_RESET_CONFIRM_SUCCESS',
    PASSWORD_RESET_CONFIRM_FAILURE: 'PASSWORD_RESET_CONFIRM_FAILURE',
};