import {
  getFinancialYears,
  getObjectives,
  getTargets,
  getActivities,
  createUpdateActivity,
  deleteActivity,
  getQuarterlyData,
  createUpdateQuarterlyData,
  getActivityDocuments,
  uploadActivityDocument,
  updateActivityDocument,
  deleteActivityDocument,
  activityApproval,
  getPerformanceAuditLogs,
  postConversationComment,
  submitActivityImplementation,
  activityImplementationApproval,
} from "../Queries";

export {
  getFinancialYears,
  getObjectives,
  getTargets,
  getActivities,
  createUpdateActivity,
  deleteActivity,
  getQuarterlyData,
  createUpdateQuarterlyData,
  getActivityDocuments,
  uploadActivityDocument,
  updateActivityDocument,
  deleteActivityDocument,
  activityApproval,
  getPerformanceAuditLogs,
  postConversationComment,
  submitActivityImplementation,
  activityImplementationApproval,
};

