export const loginTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_NEW_USER: 'LOGIN_NEW_USER',
    LOGIN_RESET_PASSWORD: 'LOGIN_RESET_PASSWORD',

};